# https://docs.travis-ci.com/user/languages/dart/
language: dart
dist: xenial
addons:
  apt:
    packages:
      - lib32stdc++6
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
  - flutter config --enable-web
  - gem install coveralls-lcov
script:
  - flutter test --coverage
  - flutter build web
after_success:
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
    - $HOME/.pub-cache

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build/web
